version: "3.3"

services:
  db:
    image: postgres:12-alpine
    container_name: geralzao-pg
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${PG_HOST}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_NAME}
    ports:
      - ${PG_PORT}:5432
    logging:
      options:
        max-size: "5m"
        max-file: "5"

  adminer:
    image: adminer
    container_name: geralzao-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
